# Generated by Django 4.0.1 on 2022-01-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contets', models.TextField()),
                ('write_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.book')),
            ],
            options={
                'db_table': 'replies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='querysets.reply')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.user', to_field='email'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('test1', models.DecimalField(decimal_places=1, max_digits=2)),
                ('test2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('test3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.user')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysets.book')),
            ],
            options={
                'db_table': 'books_authors',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author', through='querysets.BookAuthor', to='querysets.Author'),
        ),
    ]
