# Generated by Django 4.0.1 on 2022-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0002_alter_reply_email_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='test3',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
