# Generated by Django 4.0.1 on 2022-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0003_remove_rating_test1_remove_rating_test2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('toppings', models.ManyToManyField(to='querysets.Topping')),
            ],
        ),
    ]
