# Generated by Django 4.0.1 on 2022-02-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysets', '0006_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rate',
        ),
    ]
